### ISSUE TITLE
Error when trying to export plot.

### ISSUE THREAD

**Issue by nicomeza** [daniel-muthukrishna/astrodash#22]
When using the option to save the plot (Export -> Plot -> Image file) the program crashes without saving the plots.
The error output : 
-------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dustspeck/miniconda3/lib/python3.7/site-packages/pyqtgraph/exporters/Exporter.py", line 77, in fileSaveFinished
    self.export(fileName=fileName, **self.fileDialog.opts)
  File "/home/dustspeck/miniconda3/lib/python3.7/site-packages/pyqtgraph/exporters/ImageExporter.py", line 70, in export
    bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)

TypeError: 'float' object cannot be interpreted as an integer
-------------------------------------------------------------------------------------------------------------------------------------

When trying to export with the option 'Matplotlib Window' it also crashes. 

Error output : 

-------------------------------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/dustspeck/miniconda3/lib/python3.7/site-packages/pyqtgraph/GraphicsScene/exportDialog.py", line 132, in exportClicked
    self.currentExporter.export()
  File "/home/dustspeck/miniconda3/lib/python3.7/site-packages/pyqtgraph/exporters/Matplotlib.py", line 109, in export
    raise Exception("Matplotlib export currently only works with plot items")
Exception: Matplotlib export currently only works with plot items
-------------------------------------------------------------------------------------------------------------------------------------

When selecting the 'Entire scene' instead of 'Plot', saving in image format and SVG seems to work fine.

**Comment by daniel-muthukrishna** [comment]
Thank you for making me aware of this error and for suggesting a workaround. I will try to release a fix to this and add a save_plot routine in the next update.
For now, the following should work as you suggest:

**To save a plot:**
Right-click the plot, click _Export_, select _Entire Scene_, select _Image File_ or _SVG_, and save the plot appropriately.

**To save the data from the plot:**
Right-click the plot, click _Export_, select _CSV from plot data_, and save the data appropriately.

Of course, you can make your own plots with the saved data, or using the python interface.
